[2023-05-12T20:28:34.732+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-05-12T20:29:34.789+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-03-20T00:00:00+00:00 [queued]>
[2023-05-12T20:29:34.790+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-12T20:29:34.974+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-03-20 00:00:00+00:00
[2023-05-12T20:29:34.993+0000] {standard_task_runner.py:57} INFO - Started process 239 to run task
[2023-05-12T20:29:35.005+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-03-20T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpqc4fwuq_']
[2023-05-12T20:29:35.006+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask cria_pasta
[2023-05-12T20:29:35.263+0000] {task_command.py:410} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-03-20T00:00:00+00:00 [running]> on host 8e8909d3af93
[2023-05-12T20:29:35.557+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos' AIRFLOW_CTX_TASK_ID='cria_pasta' AIRFLOW_CTX_EXECUTION_DATE='2023-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-20T00:00:00+00:00'
[2023-05-12T20:29:35.564+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-12T20:29:35.604+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir "C:/DS/Airflow/Data/semana=2023-03-27"']
[2023-05-12T20:29:35.854+0000] {subprocess.py:86} INFO - Output:
[2023-05-12T20:29:36.400+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘C:/DS/Airflow/Data/semana=2023-03-27’: No such file or directory
[2023-05-12T20:29:36.412+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-12T20:29:36.433+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-12T20:29:36.454+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230320T000000, start_date=20230512T202834, end_date=20230512T202936
[2023-05-12T20:29:36.549+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 27 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 239)
[2023-05-12T20:29:36.623+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-12T20:29:36.677+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
