[2023-05-12T20:22:21.847+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-05-12T20:22:22.474+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-05-12T20:22:22.478+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-12T20:22:23.057+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-02-06 00:00:00+00:00
[2023-05-12T20:22:23.148+0000] {standard_task_runner.py:57} INFO - Started process 131 to run task
[2023-05-12T20:22:23.260+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-02-06T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp9ch5a_yf']
[2023-05-12T20:22:23.282+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask cria_pasta
[2023-05-12T20:22:23.894+0000] {task_command.py:410} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [running]> on host 8e8909d3af93
[2023-05-12T20:22:25.510+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos' AIRFLOW_CTX_TASK_ID='cria_pasta' AIRFLOW_CTX_EXECUTION_DATE='2023-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-06T00:00:00+00:00'
[2023-05-12T20:22:25.527+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-12T20:22:25.633+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir "C:/DS/Airflow/Data/semana=2023-02-13"']
[2023-05-12T20:22:25.654+0000] {subprocess.py:86} INFO - Output:
[2023-05-12T20:22:26.755+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘C:/DS/Airflow/Data/semana=2023-02-13’: No such file or directory
[2023-05-12T20:22:27.129+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-12T20:22:31.165+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-12T20:22:31.178+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230206T000000, start_date=20230512T202221, end_date=20230512T202231
[2023-05-12T20:22:32.953+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 131)
[2023-05-12T20:22:33.014+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-12T20:22:33.071+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
