[2023-05-12T20:22:09.278+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2023-05-12T20:22:09.303+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2023-05-12T20:22:09.304+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-12T20:22:09.966+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-12 00:00:00+00:00
[2023-05-12T20:22:09.986+0000] {standard_task_runner.py:57} INFO - Started process 116 to run task
[2023-05-12T20:22:10.009+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-12T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmtc7hdls']
[2023-05-12T20:22:10.015+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask cria_pasta
[2023-05-12T20:22:10.790+0000] {task_command.py:410} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [running]> on host 8e8909d3af93
[2023-05-12T20:22:11.834+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos' AIRFLOW_CTX_TASK_ID='cria_pasta' AIRFLOW_CTX_EXECUTION_DATE='2022-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-12T00:00:00+00:00'
[2023-05-12T20:22:13.019+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-12T20:22:13.323+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir "C:/DS/Airflow/Data/semana=2022-12-19"']
[2023-05-12T20:22:13.366+0000] {subprocess.py:86} INFO - Output:
[2023-05-12T20:22:17.024+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘C:/DS/Airflow/Data/semana=2022-12-19’: No such file or directory
[2023-05-12T20:22:17.042+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-12T20:22:17.876+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-12T20:22:17.888+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221212T000000, start_date=20230512T202209, end_date=20230512T202217
[2023-05-12T20:22:18.242+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 15 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 116)
[2023-05-12T20:22:18.307+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-12T20:22:18.371+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
