[2023-05-12T20:30:54.423+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-05-12T20:30:54.440+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-05-12T20:30:54.441+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-12T20:30:54.682+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-05-12T20:30:54.693+0000] {standard_task_runner.py:57} INFO - Started process 260 to run task
[2023-05-12T20:30:54.699+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpwkzhy7b5']
[2023-05-12T20:30:54.700+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask cria_pasta
[2023-05-12T20:30:54.887+0000] {task_command.py:410} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host 8e8909d3af93
[2023-05-12T20:30:55.168+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dados_climaticos' AIRFLOW_CTX_TASK_ID='cria_pasta' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2023-05-12T20:30:55.171+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-12T20:30:55.185+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir "C:/DS/Airflow/Data/semana=2023-01-09"']
[2023-05-12T20:30:55.210+0000] {subprocess.py:86} INFO - Output:
[2023-05-12T20:30:55.247+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘C:/DS/Airflow/Data/semana=2023-01-09’: No such file or directory
[2023-05-12T20:30:55.248+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-12T20:30:55.276+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-12T20:30:55.287+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230512T203054, end_date=20230512T203055
[2023-05-12T20:30:55.399+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 260)
[2023-05-12T20:30:55.434+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-12T20:30:55.485+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
